- hosts: mt-2110-3
  connection: httpapi
  tasks:
    - name: Setup gateway network for static route
      ftd_configuration:
        operation: upsertNetworkObject
        data:
          name: InternetGateway
          subType: HOST
          value: 10.10.20.1
          dnsResolution: IPV4_AND_IPV6
          type: networkobject

    - name: Get Ethernet1/4 Interface
      ftd_configuration:
        operation: getPhysicalInterfaceList
        filters:
          hardwareName: Ethernet1/4
        register_as: interface0

    - name: Get an IPv4 network
      ftd_configuration:
        operation: getNetworkObjectList
        filters:
          name: any-ipv4
        register_as: network_results

    - name: Setup static route
      ftd_configuration:
        operation: upsertStaticRouteEntry
        data:
          iface: "{{ interface0[0] }}"
          networks:
            - "{{ network_results[0] }}"
          gateway: "{{ networkobject_internetgateway }}"
          name: "test_static_route"
          metricValue: 1
          ipType: IPv4
          type: staticrouteentry
        path_params:
          parentId: default
