- hosts: mt-2110-3
  connection: httpapi
  tasks:
    - name: Get Ethernet1/4 Interface
      ftd_configuration:
        operation: getPhysicalInterfaceList
        filters:
          hardwareName: Ethernet1/4
        register_as: interface0

    - name: Get an IPv4 network
      ftd_configuration:
        operation: getNetworkObjectList
        filters:
          name: any-ipv4
        register_as: network_results

    - name: Get a before auto NAT container
      ftd_configuration:
        operation: getManualNatRuleContainerList
        filters:
          name: NGFW-Before-Auto-NAT-Policy
        register_as: container_results

    - name: Setup an Internet NAT rule
      ftd_configuration:
        operation: upsertManualNatRule
        data:
          name: InternetNatRule
          natType: DYNAMIC
          destinationInterface: "{{ interface0[0] }}"
          #sourceInterface: "{{ interface1[0] }}"
          originalSource: "{{ network_results[0] }}"
          interfaceInTranslatedSource: True
          dns: False
          enabled: True
          interfaceIPv6: False
          type: manualnatrule
        path_params:
          parentId: "{{ container_results[0].id }}"
