- hosts: mt-2110-3
  connection: httpapi
  tasks:
    - name: Get Ethernet1/1 Interface
      ftd_configuration:
        operation: getPhysicalInterfaceList
        filters:
          hardwareName: Ethernet1/1
        register_as: interface0

    - name: Setup 1st SubInterface under Ethernet1/1
      ftd_configuration:
        operation: upsertSubInterface
        data:
          name: eth1_1_3009
          hardwareName: Ethernet1/1.3009
          subIntfId: 3009
          ipv4:
            addressNull: False
            defaultRouteUsingDHCP: False
            dhcp: False
            ipAddress:
              ipAddress: 30.9.1.1
              netmask: 255.255.255.0
              standbyIpAddress: 30.9.1.2
              type: haipv4address
            ipType: STATIC
            type: interfaceipv4
          ipv6:
            enabled: True
            #autoConfig: False
            ipAddresses:
              [
                {
                  'ipAddress': '30:9:1:1:0:0:0:1/64',
                  'standbyIpAddress': '30:9:1:1::2',
                  'type': 'haipv6address'
                }
              ]
            type: interfaceipv6
          enabled: True
          vlanId: 3009
          monitorInterface: True
          mtu: 1500
          type: subinterface
        path_params:
          parentId: "{{ interface0[0].id }}"

    - name: Setup 2nd SubInterface under Ethernet1/1
      ftd_configuration:
        operation: upsertSubInterface
        data:
          name: eth1_1_3010
          hardwareName: Ethernet1/1.3010
          subIntfId: 3010
          ipv4:
            addressNull: False
            defaultRouteUsingDHCP: False
            dhcp: False
            ipAddress:
              ipAddress: 30.10.1.1
              netmask: 255.255.255.0
              standbyIpAddress: 30.10.1.2
              type: haipv4address
            ipType: STATIC
            type: interfaceipv4
          ipv6:
            enabled: True
            #autoConfig: False
            ipAddresses:
              [
                {
                  'ipAddress': '30:10:1:1::1/64',
                  'standbyIpAddress': '30:10:1:1::2',
                  'type': 'haipv6address'
                }
              ]
            type: interfaceipv6
          enabled: True
          vlanId: 3010
          monitorInterface: True
          mtu: 1500
          type: subinterface
        path_params:
          parentId: "{{ interface0[0].id }}"

    - name: Get Ethernet1/2 Interface
      ftd_configuration:
        operation: getPhysicalInterfaceList
        filters:
          hardwareName: Ethernet1/2
        register_as: interface1

    - name: Setup 1st SubInterface under Ethernet1/2
      ftd_configuration:
        operation: upsertSubInterface
        data:
          name: eth1_2_3011
          hardwareName: Ethernet1/2.3011
          subIntfId: 3011
          ipv4:
            addressNull: False
            defaultRouteUsingDHCP: False
            dhcp: False
            ipAddress:
              ipAddress: 30.11.1.1
              netmask: 255.255.255.0
              standbyIpAddress: 30.11.1.2
              type: haipv4address
            ipType: STATIC
            type: interfaceipv4
          ipv6:
            enabled: True
            #autoConfig: False
            ipAddresses:
              [
                {
                  'ipAddress': '30:11:1:1:0:0:0:1/64',
                  'standbyIpAddress': '30:11:1:1::2',
                  'type': 'haipv6address'
                }
              ]
            type: interfaceipv6
          enabled: True
          vlanId: 3011
          monitorInterface: True
          mtu: 1500
          type: subinterface
        path_params:
          parentId: "{{ interface1[0].id }}"

    - name: Setup 2nd SubInterface under Ethernet1/2
      ftd_configuration:
        operation: upsertSubInterface
        data:
          name: eth1_2_3012
          hardwareName: Ethernet1/2.3012
          subIntfId: 3012
          ipv4:
            addressNull: False
            defaultRouteUsingDHCP: False
            dhcp: False
            ipAddress:
              ipAddress: 30.12.1.1
              netmask: 255.255.255.0
              standbyIpAddress: 30.12.1.2
              type: haipv4address
            ipType: STATIC
            type: interfaceipv4
          ipv6:
            enabled: True
            #autoConfig: False
            ipAddresses:
              [
                {
                  'ipAddress': '30:12:1:1::1/64',
                  'standbyIpAddress': '30:12:1:1::2',
                  'type': 'haipv6address'
                }
              ]
            type: interfaceipv6
          enabled: True
          vlanId: 3012
          monitorInterface: True
          mtu: 1500
          type: subinterface
        path_params:
          parentId: "{{ interface1[0].id }}"




