- hosts: all
  connection: httpapi
  tasks:
    - name: Disable the identity policy from access policy
      ftd_configuration:
        operation: upsertAccessPolicy
        data:
          name: NGFW-Access-Policy
          defaultAction:
            action: PERMIT
            eventLogAction: LOG_NONE
            syslogServer: null
            intrusionPolicy:
              id: "{{ intrusion_policies[0].id }}"
              type: "{{ intrusion_policies[0].type }}"
            type: accessdefaultaction
          identityPolicySetting: null
          type: accesspolicy
