- hosts: all
  connection: httpapi
  tasks:
    - name: Create an FQDN network for Cisco DevNet
      ftd_configuration:
        operation: upsertNetworkObject
        data:
          name: CiscoDevNetNetwork
          subType: FQDN
          value: developer.cisco.com
          type: networkobject
          dnsResolution: IPV4_AND_IPV6

    - name: Create an access rule allowing trafic from Cisco DevNet
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: AllowCiscoTraffic
          type: accessrule
          sourceNetworks:
            - '{{ networkobject_ciscodevnetnetwork }}'
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
        path_params:
          parentId: default
    - name: Start deployment
      ftd_configuration:
        operation: addDeployment
        register_as: deployment_job

    - name: Poll deployment status until the job is finished
      ftd_configuration:
        operation: getDeployment
        path_params:
          objId: '{{ deployment_job.id }}'
        register_as: deployment_status
      until: deployment_status.endTime != -1
      retries: 100
      delay: 3

    - name: Stop the playbook if the deployment failed
      fail:
        msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
      when: deployment_status.state != 'DEPLOYED'

    - name: Update the access rule allowing trafic from/to Cisco DevNet
      ftd_configuration:
        operation: editAccessRule
        data:
          name: AllowCiscoTraffic
          id: '{{ accessrule_allowciscotraffic.id }}'
          ruleId: '{{ accessrule_allowciscotraffic.ruleId }}'
          version: '{{ accessrule_allowciscotraffic.version }}'
          type: accessrule
          sourceNetworks:
            - '{{ networkobject_ciscodevnetnetwork }}'
          destinationNetworks:
            - '{{ networkobject_ciscodevnetnetwork }}'
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
        path_params:
          objId: '{{ accessrule_allowciscotraffic.id }}'
          parentId: default
    - name: Start deployment
      ftd_configuration:
        operation: addDeployment
        register_as: deployment_job

    - name: Poll deployment status until the job is finished
      ftd_configuration:
        operation: getDeployment
        path_params:
          objId: '{{ deployment_job.id }}'
        register_as: deployment_status
      until: deployment_status.endTime != -1
      retries: 100
      delay: 3

    - name: Stop the playbook if the deployment failed
      fail:
        msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
      when: deployment_status.state != 'DEPLOYED'

    - name: Delete the access rule allowing trafic from/to Cisco DevNet
      ftd_configuration:
        operation: deleteAccessRule
        path_params:
          objId: '{{ accessrule_allowciscotraffic.id }}'
          parentId: default

    - name: Delete the FQDN network for Cisco DevNet
      ftd_configuration:
        operation: deleteNetworkObject
        path_params:
          objId: '{{ networkobject_ciscodevnetnetwork.id }}'

    - name: Start deployment
      ftd_configuration:
        operation: addDeployment
        register_as: deployment_job

    - name: Poll deployment status until the job is finished
      ftd_configuration:
        operation: getDeployment
        path_params:
          objId: '{{ deployment_job.id }}'
        register_as: deployment_status
      until: deployment_status.endTime != -1
      retries: 100
      delay: 3

    - name: Stop the playbook if the deployment failed
      fail:
        msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
      when: deployment_status.state != 'DEPLOYED'
