- hosts: all
  connection: httpapi
  tasks:
    - name: Setup an identity policy
      ftd_configuration:
        operation: upsertIdentityPolicy
        data:
          name: NGFW-Default-Identity-Policy
          defaultIdentityRule:
            authAction: PASSIVE
            type: defaultidentityrule
          activeAuthPort: 885
          type: identitypolicy
        register_as: identity_policy

    - name: Find an intrustion policy with maximum detection
      ftd_configuration:
        operation: getIntrusionPolicyList
        register_as: intrusion_policies

    - name: Setup a syslog server
      ftd_configuration:
        operation: upsertSyslogServer
        data:
          name: 10.10.50.5:514
          useManagementInterface: True
          protocol: UDP
          host: 10.10.50.5
          port: "514"
          type: syslogserver
        filters:
          host: 10.10.50.5
        register_as: syslog_server

    - name: Enable the identity policy as a part of access policy
      ftd_configuration:
        operation: upsertAccessPolicy
        data:
          name: NGFW-Access-Policy
          defaultAction:
            action: PERMIT
            eventLogAction: LOG_BOTH
            syslogServer: "{{ syslog_server }}"
            intrusionPolicy:
              id: "{{ intrusion_policies[0].id }}"
              type: "{{ intrusion_policies[0].type }}"
            type: accessdefaultaction
          identityPolicySetting: "{{ identity_policy }}"
          type: accesspolicy
