- hosts: all
  connection: httpapi
  tasks:
    - name: Check Licenses
      ftd_configuration:
        operation: getLicenseList
        register_as: all_license_list

    - name: Enable Malware License
      ftd_configuration:
        operation: addLicense
        data:
          licenseType: MALWARE
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["MALWARE"]) | list | length == 0'

    - name: Enable Threat License
      ftd_configuration:
        operation: addLicense
        data:
          licenseType: THREAT
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["THREAT"]) | list | length == 0'

    - name: Find an intrustion policy
      ftd_configuration:
        operation: getIntrusionPolicyList
        register_as: intrusion_policies

    - name: Find a file policy
      ftd_configuration:
        operation: getFilePolicyList
        register_as: file_policies

    - name: Create an access rule with intrusion and file policies
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: max detection and block malware rule
          ruleAction: PERMIT
          filePolicy: "{{ file_policies[0] }}"
          intrusionPolicy:
            id: "{{ intrusion_policies[0].id }}"
            type: "{{ intrusion_policies[0].type }}"
          type: accessrule
        path_params:
          parentId: default

    - name: Create an access rule with intrusion and file policies
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: ConnOverSec and Blk Office PDF and other malware rule
          ruleAction: PERMIT
          filePolicy: "{{ file_policies[1] }}"
          intrusionPolicy:
            id: "{{ intrusion_policies[1].id }}"
            type: "{{ intrusion_policies[1].type }}"
          type: accessrule
        path_params:
          parentId: default

    - name: Create an access rule with intrusion and file policies
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: BalSecCon and Blk Office and other malware rule
          ruleAction: PERMIT
          filePolicy: "{{ file_policies[2] }}"
          intrusionPolicy:
            id: "{{ intrusion_policies[2].id }}"
            type: "{{ intrusion_policies[2].type }}"
          type: accessrule
        path_params:
          parentId: default  
          
    - name: Create an access rule with intrusion and file policies
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: SecOverConn and Cloud Lookup rule
          ruleAction: PERMIT
          filePolicy: "{{ file_policies[3] }}"
          intrusionPolicy:
            id: "{{ intrusion_policies[3].id }}"
            type: "{{ intrusion_policies[3].type }}"
          type: accessrule
        path_params:
          parentId: default          
