- hosts: all
  connection: httpapi
  tasks:
    - name: Check Licenses
      ftd_configuration:
        operation: getLicenseList
        register_as: all_license_list

    - name: Enable URL License
      ftd_configuration:
        operation: addLicense
        data:
          licenseType: URLFILTERING
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["URLFILTERING"]) | list | length == 0'

    - name: Find an URL category
      ftd_configuration:
        operation: getURLCategoryList
        query_params:
          limit: 100
        register_as: category_results

    - name: Find a high risk URL reputation
      ftd_configuration:
        operation: getURLReputationList
        filters:
          startPercentage: 1
        register_as: reputation_results

    - name: Create an access rule blocking traffic
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Block traffic from URLs with high risks
          ruleAction: DENY
          eventLogAction: LOG_NONE
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[0] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[1] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[2] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[3] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[4] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[5] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[6] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[7] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[8] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[9] }}"
                urlReputation: "{{ reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default
    - name: Find a suspicious risk URL reputation
      ftd_configuration:
        operation: getURLReputationList
        filters:
          name: "Suspicious sites"
        register_as: suspicious_reputation_results

    - name: Create an access rule blocking suscpicious traffic
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Block traffic from suscpicious URLs 
          ruleAction: DENY
          eventLogAction: LOG_NONE
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[10] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[11] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[12] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[13] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[14] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[15] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[16] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[17] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[18] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[19] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default
