- hosts: all
  connection: httpapi
  tasks:
    - name: Check Licenses
      ftd_configuration:
        operation: getLicenseList
        register_as: all_license_list

    - name: Enable URL License
      ftd_configuration:
        operation: addLicense
        data:
          licenseType: URLFILTERING
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["URLFILTERING"]) | list | length == 0'

    - name: Find an URL category
      ftd_configuration:
        operation: getURLCategoryList
        query_params:
          limit: 100
        register_as: category_results

    - name: Find a high risk URL reputation
      ftd_configuration:
        operation: getURLReputationList
        filters:
          startPercentage: 1
        register_as: reputation_results

    - name: Create an access rule blocking traffic
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Block traffic from URLs with high risks
          ruleAction: DENY
          eventLogAction: LOG_BOTH
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[0] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[1] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[2] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[3] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[4] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[5] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[6] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[7] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[8] }}"
                urlReputation: "{{ reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[9] }}"
                urlReputation: "{{ reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default
    - name: Find a suspicious risk URL reputation
      ftd_configuration:
        operation: getURLReputationList
        filters:
          name: "Suspicious sites"
        register_as: suspicious_reputation_results

    - name: Create an access rule blocking suscpicious traffic
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Block traffic from suscpicious URLs 
          ruleAction: DENY
          eventLogAction: LOG_BOTH
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[10] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[11] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[12] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[13] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[14] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[15] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[16] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[17] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[18] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[19] }}"
                urlReputation: "{{ suspicious_reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default
    - name: Find a benign risk URL reputation
      ftd_configuration:
        operation: getURLReputationList
        filters:
          name: "Benign sites with security risks"
        register_as: benign_reputation_results

    - name: Create an access rule allowing benign traffic
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Allow traffic from benign URLs with security risks
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[20] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[21] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[22] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[23] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[24] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[25] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[26] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[27] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[28] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[29] }}"
                urlReputation: "{{ benign_reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default
          
    - name: Find a benign and safe URL reputation
      ftd_configuration:
        operation: getURLReputationList
        filters:
          name: "Benign sites"
        register_as: benign_safe_reputation_results

    - name: Create an access rule allowing benign traffic
      ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Allow traffic from benign URLs
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[30] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[31] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[32] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[33] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[34] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[35] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[36] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[37] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[38] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[39] }}"
                urlReputation: "{{ benign_safe_reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default          
